INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (1, 'Finland', 9.30, 70, 9.5, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (2, 'Sweden', 9.39, 89, 8.1, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (3, 'Norway', 9.81, 90, 4.4, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (4, 'Estonia', 8.13, 84, 7.5, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (5, 'Latvia', 7.66, 64, 6.7, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (6, 'Lithuania', 7.59, 75, 6.7, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (7, 'Belarus', 1.99, 12, 3.0, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (8, 'Poland', 7.40, 35, 2.7, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (9, 'Czech Republic', 8.08, 50, 2.6, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (10, 'Germany', 8.73, 56, 3.5, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (11, 'Denmark', 9.28, 86, 2.6, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (12, 'Austria', 8.28, 40, 5.4, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (13, 'Hungary', 6.51, 19, 4.2, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (14, 'Italy', 7.58, 13, 6.0, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (15, 'France', 7.99, 39, 7.3, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (16, 'Netherlands', 9.00, 95, 4.0, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (17, 'Spain', 8.13, 22, 10.9, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (18, 'Portugal', 8.08, 75, 6.5, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (19, 'Croatia', 6.50, 81, 4.7, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (20, 'Slovenia', 7.82, 74, 3.2, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (21, 'Serbia', 6.26, 43, 9.1, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (22, 'Montenegro', 6.73, 37, 10.5, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (23, 'Romania', 5.99, 30, 6.0, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (24, 'Bulgaria', 6.34, 29, 3.2, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (25, 'Cyprus', 7.38, 68, 4.0, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (26, 'Georgia', 4.70, 10, 13.3, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (27, 'Armenia', 5.35, 40, 13.6, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (28, 'Republic of Ireland', 9.19, 98, 5.0, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (29, 'Russia', 2.03, 60, 2.1, 'Europe');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (30, 'Argentina', 6.51, 13, 7.5, 'South America');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (31, 'Kazakhstan', 3.08, 35, 4.6, 'Asia');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (32, 'Thailand', 6.27, 40, 1.0, 'Asia');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (33, 'Vietnam', 2.62, 50, 2.2, 'Asia');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (34, 'Japan', 8.48, 9, 2.6, 'Asia');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (35, 'South Korea', 7.75, 40, 3.0, 'Asia');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (36, 'China', 2.11, 1, 5.1, 'Asia');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (37, 'Philippines', 6.63, 100, 4.4, 'Asia');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (38, 'Australia', 8.85, 100, 4.1, 'Oceania');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (39, 'New Zealand', 9.61, 100, 5.4, 'Oceania');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (40, 'South Africa', 7.16, 100, 31.4, 'Africa');
INSERT INTO public.country (id, name, freedom_index, english_speaking_percent, unemployment_percent, region) VALUES (41, 'Canada', 8.69, 100, 6.7, 'North America');
