INSERT INTO public.province (id, name, country_id) VALUES (1, 'British Columbia', 41);
INSERT INTO public.province (id, name, country_id) VALUES (2, 'Alberta', 41);
INSERT INTO public.province (id, name, country_id) VALUES (3, 'Ontario', 41);
INSERT INTO public.province (id, name, country_id) VALUES (4, 'Nova Scotia', 41);
INSERT INTO public.province (id, name, country_id) VALUES (5, 'Manitoba', 41);
INSERT INTO public.province (id, name, country_id) VALUES (6, 'Southern Finland', 1);
INSERT INTO public.province (id, name, country_id) VALUES (7, 'Southwest Finland', 1);
INSERT INTO public.province (id, name, country_id) VALUES (8, 'Pirkanmaa', 1);
INSERT INTO public.province (id, name, country_id) VALUES (9, 'Stockholm', 2);
INSERT INTO public.province (id, name, country_id) VALUES (10, 'Vastra Gotaland', 2);
INSERT INTO public.province (id, name, country_id) VALUES (11, 'South Sweden', 2);
INSERT INTO public.province (id, name, country_id) VALUES (12, 'Uppsala County', 2);
INSERT INTO public.province (id, name, country_id) VALUES (13, 'Oslo', 3);
INSERT INTO public.province (id, name, country_id) VALUES (14, 'Bergen Region', 3);
INSERT INTO public.province (id, name, country_id) VALUES (15, 'Buskerud', 3);
INSERT INTO public.province (id, name, country_id) VALUES (16, 'Rogaland', 3);
INSERT INTO public.province (id, name, country_id) VALUES (17, 'Sor-Trondelag', 3);
INSERT INTO public.province (id, name, country_id) VALUES (18, 'Harju', 4);
INSERT INTO public.province (id, name, country_id) VALUES (19, 'Tartu', 4);
INSERT INTO public.province (id, name, country_id) VALUES (20, 'Pärnu', 4);
INSERT INTO public.province (id, name, country_id) VALUES (21, 'Riga', 5);
INSERT INTO public.province (id, name, country_id) VALUES (22, 'Pierīga', 5);
INSERT INTO public.province (id, name, country_id) VALUES (23, 'Vidzeme', 5);
INSERT INTO public.province (id, name, country_id) VALUES (24, 'Vilnius', 6);
INSERT INTO public.province (id, name, country_id) VALUES (25, 'Kaunas', 6);
INSERT INTO public.province (id, name, country_id) VALUES (26, 'Klaipėda', 6);
INSERT INTO public.province (id, name, country_id) VALUES (27, 'Minsk', 7);
INSERT INTO public.province (id, name, country_id) VALUES (28, 'Brest', 7);
INSERT INTO public.province (id, name, country_id) VALUES (29, 'Grodno', 7);
INSERT INTO public.province (id, name, country_id) VALUES (30, 'Masovian', 8);
INSERT INTO public.province (id, name, country_id) VALUES (31, 'Lesser Poland', 8);
INSERT INTO public.province (id, name, country_id) VALUES (32, 'Pomeranian', 8);
INSERT INTO public.province (id, name, country_id) VALUES (33, 'Greater Poland', 8);
INSERT INTO public.province (id, name, country_id) VALUES (34, 'Prague', 9);
INSERT INTO public.province (id, name, country_id) VALUES (35, 'South Moravian', 9);
INSERT INTO public.province (id, name, country_id) VALUES (36, 'Berlin', 10);
INSERT INTO public.province (id, name, country_id) VALUES (37, 'Bavaria', 10);
INSERT INTO public.province (id, name, country_id) VALUES (38, 'Hamburg', 10);
INSERT INTO public.province (id, name, country_id) VALUES (39, 'North Rhine-Westphalia', 10);
INSERT INTO public.province (id, name, country_id) VALUES (40, 'Bremen', 10);
INSERT INTO public.province (id, name, country_id) VALUES (41, 'Saxony', 10);
INSERT INTO public.province (id, name, country_id) VALUES (42, 'Hesse', 10);
INSERT INTO public.province (id, name, country_id) VALUES (43, 'Capital Region', 11);
INSERT INTO public.province (id, name, country_id) VALUES (44, 'Central Denmark', 11);
INSERT INTO public.province (id, name, country_id) VALUES (45, 'North Jutland', 11);
INSERT INTO public.province (id, name, country_id) VALUES (46, 'Vienna', 12);
INSERT INTO public.province (id, name, country_id) VALUES (47, 'Salzburg', 12);
INSERT INTO public.province (id, name, country_id) VALUES (48, 'Tyrol', 12);
INSERT INTO public.province (id, name, country_id) VALUES (49, 'Styria', 12);
INSERT INTO public.province (id, name, country_id) VALUES (50, 'Upper Austria', 12);
INSERT INTO public.province (id, name, country_id) VALUES (51, 'Central Hungary', 13);
INSERT INTO public.province (id, name, country_id) VALUES (52, 'Northern Great Plain', 13);
INSERT INTO public.province (id, name, country_id) VALUES (53, 'Southern Great Plain', 13);
INSERT INTO public.province (id, name, country_id) VALUES (54, 'Lombardy', 14);
INSERT INTO public.province (id, name, country_id) VALUES (55, 'Lazio', 14);
INSERT INTO public.province (id, name, country_id) VALUES (56, 'Sicily', 14);
INSERT INTO public.province (id, name, country_id) VALUES (57, 'Veneto', 14);
INSERT INTO public.province (id, name, country_id) VALUES (58, 'Emilia-Romagna', 14);
INSERT INTO public.province (id, name, country_id) VALUES (59, 'Campania', 14);
INSERT INTO public.province (id, name, country_id) VALUES (60, 'Tuscany', 14);
INSERT INTO public.province (id, name, country_id) VALUES (61, 'Île-de-France', 15);
INSERT INTO public.province (id, name, country_id) VALUES (62, 'Auvergne-Rhône-Alpes', 15);
INSERT INTO public.province (id, name, country_id) VALUES (63, 'Nouvelle-Aquitaine', 15);
INSERT INTO public.province (id, name, country_id) VALUES (64, 'Occitania', 15);
INSERT INTO public.province (id, name, country_id) VALUES (65, 'Brittany', 15);
INSERT INTO public.province (id, name, country_id) VALUES (66, 'Pays de la Loire', 15);
INSERT INTO public.province (id, name, country_id) VALUES (67, 'North Holland', 16);
INSERT INTO public.province (id, name, country_id) VALUES (68, 'South Holland', 16);
INSERT INTO public.province (id, name, country_id) VALUES (69, 'Utrecht', 16);
INSERT INTO public.province (id, name, country_id) VALUES (70, 'Catalonia', 17);
INSERT INTO public.province (id, name, country_id) VALUES (71, 'Madrid', 17);
INSERT INTO public.province (id, name, country_id) VALUES (72, 'Valencia', 17);
INSERT INTO public.province (id, name, country_id) VALUES (73, 'Basque Country', 17);
INSERT INTO public.province (id, name, country_id) VALUES (74, 'Asturias', 17);
INSERT INTO public.province (id, name, country_id) VALUES (75, 'Galicia', 17);
INSERT INTO public.province (id, name, country_id) VALUES (76, 'Andalusia', 17);
INSERT INTO public.province (id, name, country_id) VALUES (77, 'Lisbon Region', 18);
INSERT INTO public.province (id, name, country_id) VALUES (78, 'North Region', 18);
INSERT INTO public.province (id, name, country_id) VALUES (79, 'Zagreb', 19);
INSERT INTO public.province (id, name, country_id) VALUES (80, 'Istria County', 19);
INSERT INTO public.province (id, name, country_id) VALUES (81, 'Split-Dalmatia', 19);
INSERT INTO public.province (id, name, country_id) VALUES (82, 'Dubrovnik-Neretva', 19);
INSERT INTO public.province (id, name, country_id) VALUES (83, 'Central Slovenia', 20);
INSERT INTO public.province (id, name, country_id) VALUES (84, 'Belgrade', 21);
INSERT INTO public.province (id, name, country_id) VALUES (85, 'South Bačka', 21);
INSERT INTO public.province (id, name, country_id) VALUES (86, 'Southern and Eastern', 21);
INSERT INTO public.province (id, name, country_id) VALUES (87, 'Central', 22);
INSERT INTO public.province (id, name, country_id) VALUES (88, 'București - Ilfov', 23);
INSERT INTO public.province (id, name, country_id) VALUES (89, 'Nord-Vest', 23);
INSERT INTO public.province (id, name, country_id) VALUES (90, 'Vest', 23);
INSERT INTO public.province (id, name, country_id) VALUES (91, 'Yugozapaden', 24);
INSERT INTO public.province (id, name, country_id) VALUES (92, 'Yuzhen Tsentralen', 24);
INSERT INTO public.province (id, name, country_id) VALUES (93, 'Severoiztochen', 24);
INSERT INTO public.province (id, name, country_id) VALUES (94, 'Paphos', 25);
INSERT INTO public.province (id, name, country_id) VALUES (95, 'Nicosia', 25);
INSERT INTO public.province (id, name, country_id) VALUES (96, 'Larnaca', 25);
INSERT INTO public.province (id, name, country_id) VALUES (97, 'Tbilisi', 26);
INSERT INTO public.province (id, name, country_id) VALUES (98, 'Adjara', 26);
INSERT INTO public.province (id, name, country_id) VALUES (99, 'Yerevan', 27);
INSERT INTO public.province (id, name, country_id) VALUES (100, 'Dublin', 28);
INSERT INTO public.province (id, name, country_id) VALUES (101, 'County Cork', 28);
INSERT INTO public.province (id, name, country_id) VALUES (102, 'Kaliningrad', 29);
INSERT INTO public.province (id, name, country_id) VALUES (103, 'Buenos Aires', 30);
INSERT INTO public.province (id, name, country_id) VALUES (104, 'Astana', 31);
INSERT INTO public.province (id, name, country_id) VALUES (105, 'Almaty', 31);
INSERT INTO public.province (id, name, country_id) VALUES (106, 'Bangkok', 32);
INSERT INTO public.province (id, name, country_id) VALUES (107, 'Phuket province', 32);
INSERT INTO public.province (id, name, country_id) VALUES (108, 'Chonburi', 32);
INSERT INTO public.province (id, name, country_id) VALUES (109, 'Da Nang', 33);
INSERT INTO public.province (id, name, country_id) VALUES (110, 'Nha Trang', 33);
INSERT INTO public.province (id, name, country_id) VALUES (111, 'Kanto', 34);
INSERT INTO public.province (id, name, country_id) VALUES (112, 'Kansai', 34);
INSERT INTO public.province (id, name, country_id) VALUES (113, 'Tōkai', 34);
INSERT INTO public.province (id, name, country_id) VALUES (114, 'Kyushu', 34);
INSERT INTO public.province (id, name, country_id) VALUES (115, 'Hokkaido', 34);
INSERT INTO public.province (id, name, country_id) VALUES (116, 'Capital Area', 35);
INSERT INTO public.province (id, name, country_id) VALUES (117, 'Gyeongnam', 35);
INSERT INTO public.province (id, name, country_id) VALUES (118, 'Jeju', 35);
INSERT INTO public.province (id, name, country_id) VALUES (119, 'Hong Kong', 36);
INSERT INTO public.province (id, name, country_id) VALUES (120, 'Shanghai', 36);
INSERT INTO public.province (id, name, country_id) VALUES (121, 'Beijing', 36);
INSERT INTO public.province (id, name, country_id) VALUES (122, 'Guangdong', 36);
INSERT INTO public.province (id, name, country_id) VALUES (123, 'Fujian', 36);
INSERT INTO public.province (id, name, country_id) VALUES (124, 'Zhejiang', 36);
INSERT INTO public.province (id, name, country_id) VALUES (125, 'Jiangsu', 36);
INSERT INTO public.province (id, name, country_id) VALUES (126, 'Metro Manila', 37);
INSERT INTO public.province (id, name, country_id) VALUES (127, 'Central Visayas', 37);
INSERT INTO public.province (id, name, country_id) VALUES (128, 'Davao City', 37);
INSERT INTO public.province (id, name, country_id) VALUES (129, 'Victoria', 38);
INSERT INTO public.province (id, name, country_id) VALUES (130, 'New South Wales', 38);
INSERT INTO public.province (id, name, country_id) VALUES (131, 'Queensland', 38);
INSERT INTO public.province (id, name, country_id) VALUES (132, 'Western Australia', 38);
INSERT INTO public.province (id, name, country_id) VALUES (133, 'Auckland', 39);
INSERT INTO public.province (id, name, country_id) VALUES (134, 'Wellington', 39);
INSERT INTO public.province (id, name, country_id) VALUES (135, 'Cantebury', 39);
INSERT INTO public.province (id, name, country_id) VALUES (136, 'Western Cape', 40);
INSERT INTO public.province (id, name, country_id) VALUES (137, 'Eastern Cape', 40);
