INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 4, 22, null, 8400, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 5, 22.5, null, 0, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 5, 33, null, 105300, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 6, 20, null, 0, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 6, 32, null, 126532, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 22, 9, null, 8400, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 22, 15, null, 12000, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 12, 20, null, 13539, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 12, 30, null, 21992, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 12, 40, null, 36458, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 12, 48, null, 70365, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 12, 50, null, 104859, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 13, 15, null, 0, 'HUF', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 20, 16, null, 0, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 20, 26, null, 9721, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 20, 33, null, 28592, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 20, 39, null, 57184, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 20, 50, null, 82346, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 23, 10, null, 3600, 'RON', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 24, 10, null, 0, 'BGN', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 26, 20, null, 0, 'GEL', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 27, 20, null, 0, 'AMD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 7, 13, null, 0, 'BYN', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 7, 25, null, 350000, 'BYN', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 28, 20, null, 0, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 28, 40, null, 44000, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 25, 20, null, 22001, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 25, 25, null, 32001, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 25, 30, null, 42001, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 25, 35, null, 72000, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 9, 15, null, 0, 'CZK', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 9, 23, null, 1762812, 'CZK', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 8, 12, null, 30000, 'PLN', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 8, 32, null, 120000, 'PLN', 10800);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 15, 11, null, 11601, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 15, 30, null, 29580, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 15, 41, null, 84578, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 15, 45, null, 181917, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 18, 12.5, null, 0, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 18, 15.7, null, 8342, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 18, 21.2, null, 12587, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 18, 24.1, null, 17838, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 18, 31.1, null, 23089, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 18, 34.9, null, 29397, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 18, 43.1, null, 43090, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 18, 44.6, null, 46566, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 18, 48, null, 86634, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 31, 10, null, 0, 'KZT', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 31, 15, null, 36762500, 'KZT', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 32, 5, null, 150001, 'THB', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 32, 10, null, 300001, 'THB', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 32, 15, null, 500001, 'THB', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 32, 20, null, 750001, 'THB', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 32, 25, null, 1000001, 'THB', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 32, 30, null, 2000001, 'THB', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 32, 35, null, 5000000, 'THB', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 33, 5, null, 0, 'VND', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 33, 10, null, 10000000, 'VND', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 33, 20, null, 30000000, 'VND', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 33, 30, null, 60000000, 'VND', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 33, 35, null, 100000000, 'VND', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 37, 15, null, 250000, 'PHP', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 37, 20, null, 400000, 'PHP', 22500);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 37, 25, null, 800000, 'PHP', 102500);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 37, 30, null, 2000000, 'PHP', 402500);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 37, 45, null, 8000000, 'PHP', 2202500);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 21, 10, null, 5439096, 'RSD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 21, 15, null, 10878192, 'RSD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 39, 10.5, null, 0, 'NZD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 39, 17.5, null, 15601, 'NZD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 39, 30, null, 53501, 'NZD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 39, 33, null, 78101, 'NZD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 39, 39, null, 180001, 'NZD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 40, 18, null, 1, 'ZAR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 40, 26, null, 245101, 'ZAR', 44118);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 40, 31, null, 383101, 'ZAR', 79998);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 40, 36, null, 530201, 'ZAR', 125599);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 40, 39, null, 695801, 'ZAR', 185215);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 40, 41, null, 887001, 'ZAR', 259783);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 40, 45, null, 1878601, 'ZAR', 666339);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 30, 5, null, 0, 'ARS', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 30, 9, null, 2000030, 'ARS', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 30, 12, null, 4000060, 'ARS', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 30, 15, null, 6000090, 'ARS', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 30, 19, null, 9000135, 'ARS', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 30, 23, null, 18000270, 'ARS', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 30, 27, null, 27000405, 'ARS', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 30, 31, null, 40500607, 'ARS', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 30, 35, null, 60750914, 'ARS', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 38, 16, null, 18201, 'AUD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 38, 30, null, 45001, 'AUD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 38, 37, null, 135001, 'AUD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 38, 45, null, 190000, 'AUD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 41, 14, null, 0, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 41, 20.5, null, 58523, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 41, 26, null, 117045, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 41, 29, null, 181440, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 41, 33, null, 258482, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 3, 41, 5.05, null, 0, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 3, 41, 9.15, null, 52886, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 3, 41, 11.16, null, 105773, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 3, 41, 12.16, null, 150000, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 3, 41, 13.16, null, 220000, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 2, 41, 8, null, 0, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 2, 41, 10, null, 61200, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 2, 41, 12, null, 154259, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 2, 41, 13, null, 185111, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 2, 41, 14, null, 246813, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 2, 41, 15, null, 370220, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 1, 41, 5.06, null, 0, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 1, 41, 7.7, null, 50363, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 1, 41, 10.05, null, 100728, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 1, 41, 12.29, null, 115648, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 1, 41, 14.7, null, 140430, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 1, 41, 16.8, null, 190405, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 1, 41, 20.5, null, 265545, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 4, 41, 8.79, null, 0, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 4, 41, 14.95, null, 30995, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 4, 41, 16.67, null, 61991, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 4, 41, 17.5, null, 97417, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 4, 41, 21, null, 157124, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 5, 41, 10.8, null, 0, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 5, 41, 12.75, null, 47001, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('province', null, 5, 41, 17.4, null, 100000, 'CAD', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 17, 19, null, 0, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 17, 24, null, 12451, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 17, 30, null, 20201, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 17, 37, null, 35201, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 17, 45, null, 60001, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 17, 47, null, 300000, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 14, 26.7, null, 0, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 14, 38.7, null, 28001, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 14, 46.7, null, 50000, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 29, 13, null, 0, 'RUB', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 29, 15, null, 2400000, 'RUB', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 29, 18, null, 5000000, 'RUB', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 29, 20, null, 20000000, 'RUB', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 29, 22, null, 50000000, 'RUB', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 1, 12.64, null, 0, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 1, 19, null, 22000, 'EUR', 2781);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 1, 30.25, null, 32600, 'EUR', 4795);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 1, 33.25, null, 40100, 'EUR', 7064);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 1, 37.5, null, 52100, 'EUR', 11053);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('city', 10, null, 1, 5.3, null, 0, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('city', 11, null, 1, 7.1, null, 0, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('city', 12, null, 1, 7.6, null, 0, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 2, 20, null, 625800, 'SEK', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('city', 13, null, 2, 32, null, 0, 'SEK', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('city', 16, null, 2, 32, null, 0, 'SEK', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('city', 17, null, 2, 32, null, 0, 'SEK', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('city', 18, null, 2, 32, null, 0, 'SEK', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 3, 22, null, 114501, 'NOK', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 3, 1.7, null, 226101, 'NOK', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 3, 4, null, 318301, 'NOK', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 3, 13.7, null, 725051, 'NOK', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 3, 16.8, null, 980101, 'NOK', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 3, 17.8, null, 1467201, 'NOK', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 16, 35.7, null, 0, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 16, 37.56, null, 38883, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 16, 49.5, null, 78426, 'EUR', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 36, 3, null, 0, 'CNY', null);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 36, 10, null, 36000, 'CNY', 2520);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 36, 20, null, 144000, 'CNY', 16920);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 36, 25, null, 300000, 'CNY', 31920);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 36, 30, null, 420000, 'CNY', 52920);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 36, 35, null, 660000, 'CNY', 85920);
INSERT INTO public.tax (jurisdiction, city_id, province_id, country_id, percent_from, percent_to, tax_from, currency, fixed_tax) VALUES ('federal', null, null, 36, 45, null, 960000, 'CNY', 181920);

insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Croatia'),20,0,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'France'),23,0,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Italy'),10,0,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Spain'),6.5,0,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Netherlands'),27.65,0,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Norway'),7.6,0,'NOK');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Poland'),13.71,0,'PLN');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Czech Republic'),11.6,0,'CZK');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Austria'),18.10,0,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Hungary'),18.5,0,'HUF');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Slovenia'),22.1,0,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Serbia'),19.9,0,'RSD');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Romania'),35,0,'RON');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Republic of Ireland'),4.2,16896,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Republic of Ireland'),0.5,0,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Republic of Ireland'),2,12012,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Republic of Ireland'),3,27700,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Republic of Ireland'),8,70000,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Republic of Ireland'),11,100000,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Belarus'),1,0,'BYN');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Vietnam'),10.5,0,'VND');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'South Africa'),1,0,'ZAR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Estonia'),1.6,0,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Latvia'),10.5,0,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Lithuania'),19.5,0,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Finland'),9.17,0,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Denmark'),8,0,'DKK');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Portugal'),11,0,'EUR');
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'Georgia'),2,0,'GEL');





insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'Japan'),9.15,0,'JPY',7800000);
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'Japan'),4.995,0,'JPY',16680000);

insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'Philippines'),7.5,0,'PHP',51000);

insert into tax  (jurisdiction, country_id,city_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'China'),(select id from city where name = 'Shanghai'),10.5,0,'CNY',447624);
insert into tax  (jurisdiction, country_id,city_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'China'),(select id from city where name = 'Guangzhou'),10.2,0,'CNY',493344);
insert into tax  (jurisdiction, country_id,city_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'China'),(select id from city where name = 'Beijing'),10.2,0,'CNY',493344);
insert into tax  (jurisdiction, country_id,city_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'China'),(select id from city where name = 'Nanjing'),10.5,0,'CNY',408000);
insert into tax  (jurisdiction, country_id,city_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'China'),(select id from city where name = 'Xiamen'),10.5,0,'CNY',336000);
insert into tax  (jurisdiction, country_id,city_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'China'),(select id from city where name = 'Hangzhou'),10.5,0,'CNY',396000);
insert into tax  (jurisdiction, country_id,city_id, percent_from, tax_from, currency,tax_limit,income_floor) values ('social',(select id from country where name = 'China'),(select id from city where name = 'Hong Kong'),5,0,'HKD',18000,85200);

insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'Argentina'),17,0,'ARS',44774544);

insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'Sweden'),7,0,'SEK',47100);

insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'Germany'),9.3,0,'EUR',101400);
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'Germany'),8.75,0,'EUR',69700);

insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'Thailand'),5,0,'THB',210000);

insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'South Korea'),4.75,0,'KRW',7068000);
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'South Korea'),4.0674,0,'KRW',124682640);
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency) values ('social',(select id from country where name = 'South Korea'),0.9,0,'KRW');

insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'Canada'),5.95,0,'CAD',4310);
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'Canada'),9.95,69700,'CAD',416);
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'Canada'),1.63,0,'CAD',1123);

insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'Armenia'),5,0,'AMD',1050000);
insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency,tax_limit,income_floor) values ('social',(select id from country where name = 'Armenia'),5,0,'AMD',1050000,6000000);


insert into tax  (jurisdiction, country_id, percent_from, tax_from, currency,tax_limit) values ('social',(select id from country where name = 'Bulgaria'),13.78,0,'BGN',46200);
update tax set exempt_percent = (select percent_from from tax where jurisdiction = 'social' and country_id =(select id from country where name = 'Bulgaria')) where jurisdiction = 'federal' AND country_id = (select id from country where name = 'Bulgaria');




insert into tax  (jurisdiction, country_id,city_id, percent_from, tax_from, currency,exempt_percent) values ('city',(select id from country where name = 'Croatia'),(select id from city where name = 'Zagreb'),23,7200,'EUR',(select percent_from from tax where jurisdiction = 'social' and country_id =(select id from country where name = 'Croatia')));
insert into tax  (jurisdiction, country_id,city_id, percent_from, tax_from, currency,exempt_percent) values ('city',(select id from country where name = 'Croatia'),(select id from city where name = 'Zagreb'),33,67200,'EUR',(select percent_from from tax where jurisdiction = 'social' and country_id =(select id from country where name = 'Croatia')));

insert into tax  (jurisdiction, country_id,city_id, percent_from, tax_from, currency,exempt_percent) values ('city',(select id from country where name = 'Croatia'),(select id from city where name = 'Pula'),22,7200,'EUR',(select percent_from from tax where jurisdiction = 'social' and country_id =(select id from country where name = 'Croatia')));
insert into tax  (jurisdiction, country_id,city_id, percent_from, tax_from, currency,exempt_percent) values ('city',(select id from country where name = 'Croatia'),(select id from city where name = 'Pula'),32,67200,'EUR',(select percent_from from tax where jurisdiction = 'social' and country_id =(select id from country where name = 'Croatia')));

insert into tax  (jurisdiction, country_id,city_id, percent_from, tax_from, currency,exempt_percent) values ('city',(select id from country where name = 'Croatia'),(select id from city where name = 'Split'),23,7200,'EUR',(select percent_from from tax where jurisdiction = 'social' and country_id =(select id from country where name = 'Croatia')));
insert into tax  (jurisdiction, country_id,city_id, percent_from, tax_from, currency,exempt_percent) values ('city',(select id from country where name = 'Croatia'),(select id from city where name = 'Split'),33,67200,'EUR',(select percent_from from tax where jurisdiction = 'social' and country_id =(select id from country where name = 'Croatia')));

insert into tax  (jurisdiction, country_id,city_id, percent_from, tax_from, currency,exempt_percent) values ('city',(select id from country where name = 'Croatia'),(select id from city where name = 'Dubrovnik'),22,7200,'EUR',(select percent_from from tax where jurisdiction = 'social' and country_id =(select id from country where name = 'Croatia')));
insert into tax  (jurisdiction, country_id,city_id, percent_from, tax_from, currency,exempt_percent) values ('city',(select id from country where name = 'Croatia'),(select id from city where name = 'Dubrovnik'),32,67200,'EUR',(select percent_from from tax where jurisdiction = 'social' and country_id =(select id from country where name = 'Croatia')));
